{% set name = "hg-setup" %}
{% set version = "0.1.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hg_setup-{{ version }}.tar.gz
  sha256: 6f8d1993dbcca0b98e47756182517f33588557fb2900742c78d77d9bee9023c8

build:
  entry_points:
    - hg-setup = hg_setup:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - click
    - textual
    - rich-click

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - hg_setup
  commands:
    - pip check
    - hg-setup --help
    - hg-setup init --help

about:
  summary: Helper for setting up and configuring Mercurial
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://foss.heptapod.net/fluiddyn/hg-setup

extra:
  recipe-maintainers:
    - paugier
